name: Heartbeat

on:
  schedule:
    - cron: '0 7 * * *'   # 10:00 по Киеву
  workflow_dispatch:       # ручной запуск

permissions:
  contents: write

concurrency:
  group: heartbeater
  cancel-in-progress: false

jobs:
  beat:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true   # использовать GITHUB_TOKEN для push

      - name: Commit & Push
        run: |
          git config user.name "dant1k"
          git config user.email "98425972+dant1k@users.noreply.github.com"
          ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # создаём/обновляем heartbeat.md, чтобы всегда были изменения
          echo "last run at $ts" > heartbeat.md

          git add heartbeat.md
          git commit -m "ci: heartbeat $ts" || echo "no changes"
          git push

